################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bl2_main.c \
/Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Middlewares/Third_Party/trustedfirmware/bl2/src/flash_map.c \
/Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/flash_map_extended.c \
/Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/flash_map_legacy.c \
/Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Middlewares/Third_Party/trustedfirmware/bl2/src/security_cnt.c \
/Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Middlewares/Third_Party/trustedfirmware/platform/ext/common/uart_stdout.c 

OBJS += \
./Middlewares/trustedfirmware/bl2_main.o \
./Middlewares/trustedfirmware/flash_map.o \
./Middlewares/trustedfirmware/flash_map_extended.o \
./Middlewares/trustedfirmware/flash_map_legacy.o \
./Middlewares/trustedfirmware/security_cnt.o \
./Middlewares/trustedfirmware/uart_stdout.o 

C_DEPS += \
./Middlewares/trustedfirmware/bl2_main.d \
./Middlewares/trustedfirmware/flash_map.d \
./Middlewares/trustedfirmware/flash_map_extended.d \
./Middlewares/trustedfirmware/flash_map_legacy.d \
./Middlewares/trustedfirmware/security_cnt.d \
./Middlewares/trustedfirmware/uart_stdout.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/trustedfirmware/bl2_main.o: /Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bl2_main.c Middlewares/trustedfirmware/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DSTM32U585xx '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' -DUSE_HAL_DRIVER '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' -DBOOT_MAX_ALIGN=16 -DBL2 -DMCUBOOT_DOUBLE_SIGN_VERIF -DFLOW_CONTROL -DNDEBUG -DTFM_DEV_MODE -DDEFAULT_UART_BAUDRATE=115200 -c -I../../Inc -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../../Drivers/BSP/B-U585I-IOT02A -I../../../../../../../Drivers/BSP/Components/Common -I../../../Linker -I../../../../../../../Middlewares/Third_Party/mbed-crypto/include -I../../../../../../../Middlewares/Third_Party/mbed-crypto/include/psa -I../../../../../../../Middlewares/Third_Party/mbed-crypto/library -I../../../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/include -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../../../Middlewares/Third_Party/mcuboot/boot/bootutil/include -I../../../../../../../Middlewares/Third_Party/mcuboot/boot/bootutil/src -I../../../../../../../Middlewares/Third_Party/mcuboot/ext/tinycrypt/lib/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/flash_map.o: /Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Middlewares/Third_Party/trustedfirmware/bl2/src/flash_map.c Middlewares/trustedfirmware/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DSTM32U585xx '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' -DUSE_HAL_DRIVER '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' -DBOOT_MAX_ALIGN=16 -DBL2 -DMCUBOOT_DOUBLE_SIGN_VERIF -DFLOW_CONTROL -DNDEBUG -DTFM_DEV_MODE -DDEFAULT_UART_BAUDRATE=115200 -c -I../../Inc -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../../Drivers/BSP/B-U585I-IOT02A -I../../../../../../../Drivers/BSP/Components/Common -I../../../Linker -I../../../../../../../Middlewares/Third_Party/mbed-crypto/include -I../../../../../../../Middlewares/Third_Party/mbed-crypto/include/psa -I../../../../../../../Middlewares/Third_Party/mbed-crypto/library -I../../../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/include -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../../../Middlewares/Third_Party/mcuboot/boot/bootutil/include -I../../../../../../../Middlewares/Third_Party/mcuboot/boot/bootutil/src -I../../../../../../../Middlewares/Third_Party/mcuboot/ext/tinycrypt/lib/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/flash_map_extended.o: /Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/flash_map_extended.c Middlewares/trustedfirmware/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DSTM32U585xx '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' -DUSE_HAL_DRIVER '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' -DBOOT_MAX_ALIGN=16 -DBL2 -DMCUBOOT_DOUBLE_SIGN_VERIF -DFLOW_CONTROL -DNDEBUG -DTFM_DEV_MODE -DDEFAULT_UART_BAUDRATE=115200 -c -I../../Inc -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../../Drivers/BSP/B-U585I-IOT02A -I../../../../../../../Drivers/BSP/Components/Common -I../../../Linker -I../../../../../../../Middlewares/Third_Party/mbed-crypto/include -I../../../../../../../Middlewares/Third_Party/mbed-crypto/include/psa -I../../../../../../../Middlewares/Third_Party/mbed-crypto/library -I../../../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/include -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../../../Middlewares/Third_Party/mcuboot/boot/bootutil/include -I../../../../../../../Middlewares/Third_Party/mcuboot/boot/bootutil/src -I../../../../../../../Middlewares/Third_Party/mcuboot/ext/tinycrypt/lib/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/flash_map_legacy.o: /Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/flash_map_legacy.c Middlewares/trustedfirmware/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DSTM32U585xx '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' -DUSE_HAL_DRIVER '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' -DBOOT_MAX_ALIGN=16 -DBL2 -DMCUBOOT_DOUBLE_SIGN_VERIF -DFLOW_CONTROL -DNDEBUG -DTFM_DEV_MODE -DDEFAULT_UART_BAUDRATE=115200 -c -I../../Inc -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../../Drivers/BSP/B-U585I-IOT02A -I../../../../../../../Drivers/BSP/Components/Common -I../../../Linker -I../../../../../../../Middlewares/Third_Party/mbed-crypto/include -I../../../../../../../Middlewares/Third_Party/mbed-crypto/include/psa -I../../../../../../../Middlewares/Third_Party/mbed-crypto/library -I../../../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/include -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../../../Middlewares/Third_Party/mcuboot/boot/bootutil/include -I../../../../../../../Middlewares/Third_Party/mcuboot/boot/bootutil/src -I../../../../../../../Middlewares/Third_Party/mcuboot/ext/tinycrypt/lib/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/security_cnt.o: /Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Middlewares/Third_Party/trustedfirmware/bl2/src/security_cnt.c Middlewares/trustedfirmware/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DSTM32U585xx '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' -DUSE_HAL_DRIVER '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' -DBOOT_MAX_ALIGN=16 -DBL2 -DMCUBOOT_DOUBLE_SIGN_VERIF -DFLOW_CONTROL -DNDEBUG -DTFM_DEV_MODE -DDEFAULT_UART_BAUDRATE=115200 -c -I../../Inc -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../../Drivers/BSP/B-U585I-IOT02A -I../../../../../../../Drivers/BSP/Components/Common -I../../../Linker -I../../../../../../../Middlewares/Third_Party/mbed-crypto/include -I../../../../../../../Middlewares/Third_Party/mbed-crypto/include/psa -I../../../../../../../Middlewares/Third_Party/mbed-crypto/library -I../../../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/include -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../../../Middlewares/Third_Party/mcuboot/boot/bootutil/include -I../../../../../../../Middlewares/Third_Party/mcuboot/boot/bootutil/src -I../../../../../../../Middlewares/Third_Party/mcuboot/ext/tinycrypt/lib/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/uart_stdout.o: /Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Middlewares/Third_Party/trustedfirmware/platform/ext/common/uart_stdout.c Middlewares/trustedfirmware/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DSTM32U585xx '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' -DUSE_HAL_DRIVER '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' -DBOOT_MAX_ALIGN=16 -DBL2 -DMCUBOOT_DOUBLE_SIGN_VERIF -DFLOW_CONTROL -DNDEBUG -DTFM_DEV_MODE -DDEFAULT_UART_BAUDRATE=115200 -c -I../../Inc -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../../Drivers/BSP/B-U585I-IOT02A -I../../../../../../../Drivers/BSP/Components/Common -I../../../Linker -I../../../../../../../Middlewares/Third_Party/mbed-crypto/include -I../../../../../../../Middlewares/Third_Party/mbed-crypto/include/psa -I../../../../../../../Middlewares/Third_Party/mbed-crypto/library -I../../../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/include -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../../../Middlewares/Third_Party/mcuboot/boot/bootutil/include -I../../../../../../../Middlewares/Third_Party/mcuboot/boot/bootutil/src -I../../../../../../../Middlewares/Third_Party/mcuboot/ext/tinycrypt/lib/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-trustedfirmware

clean-Middlewares-2f-trustedfirmware:
	-$(RM) ./Middlewares/trustedfirmware/bl2_main.cyclo ./Middlewares/trustedfirmware/bl2_main.d ./Middlewares/trustedfirmware/bl2_main.o ./Middlewares/trustedfirmware/bl2_main.su ./Middlewares/trustedfirmware/flash_map.cyclo ./Middlewares/trustedfirmware/flash_map.d ./Middlewares/trustedfirmware/flash_map.o ./Middlewares/trustedfirmware/flash_map.su ./Middlewares/trustedfirmware/flash_map_extended.cyclo ./Middlewares/trustedfirmware/flash_map_extended.d ./Middlewares/trustedfirmware/flash_map_extended.o ./Middlewares/trustedfirmware/flash_map_extended.su ./Middlewares/trustedfirmware/flash_map_legacy.cyclo ./Middlewares/trustedfirmware/flash_map_legacy.d ./Middlewares/trustedfirmware/flash_map_legacy.o ./Middlewares/trustedfirmware/flash_map_legacy.su ./Middlewares/trustedfirmware/security_cnt.cyclo ./Middlewares/trustedfirmware/security_cnt.d ./Middlewares/trustedfirmware/security_cnt.o ./Middlewares/trustedfirmware/security_cnt.su ./Middlewares/trustedfirmware/uart_stdout.cyclo ./Middlewares/trustedfirmware/uart_stdout.d ./Middlewares/trustedfirmware/uart_stdout.o ./Middlewares/trustedfirmware/uart_stdout.su

.PHONY: clean-Middlewares-2f-trustedfirmware

