################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Projects/B-U585I-IOT02A/Applications/OpenBootloader/Core/Src/main.c \
/Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Projects/B-U585I-IOT02A/Applications/OpenBootloader/Core/Src/stm32u5xx_hal_msp.c \
/Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Projects/B-U585I-IOT02A/Applications/OpenBootloader/Core/Src/stm32u5xx_hal_timebase_tim.c \
/Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Projects/B-U585I-IOT02A/Applications/OpenBootloader/Core/Src/stm32u5xx_it.c \
../Application/Core/syscalls.c \
../Application/Core/sysmem.c 

S_UPPER_SRCS += \
/Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Projects/B-U585I-IOT02A/Applications/OpenBootloader/Core/Src/tx_initialize_low_level.S 

OBJS += \
./Application/Core/main.o \
./Application/Core/stm32u5xx_hal_msp.o \
./Application/Core/stm32u5xx_hal_timebase_tim.o \
./Application/Core/stm32u5xx_it.o \
./Application/Core/syscalls.o \
./Application/Core/sysmem.o \
./Application/Core/tx_initialize_low_level.o 

S_UPPER_DEPS += \
./Application/Core/tx_initialize_low_level.d 

C_DEPS += \
./Application/Core/main.d \
./Application/Core/stm32u5xx_hal_msp.d \
./Application/Core/stm32u5xx_hal_timebase_tim.d \
./Application/Core/stm32u5xx_it.d \
./Application/Core/syscalls.d \
./Application/Core/sysmem.d 


# Each subdirectory must supply rules for building sources it contributes
Application/Core/main.o: /Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Projects/B-U585I-IOT02A/Applications/OpenBootloader/Core/Src/main.c Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSBPD_PORT_COUNT=1 -DSTM32U585xx -DUSE_HAL_DRIVER -DUSBPD_THREADX -DUSE_FULL_LL_DRIVER -DUSBPDCORE_LIB_NO_PD -DTCPP0203_SUPPORT -D_SNK -DUX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_B_U585I_IOT02A -DTX_SINGLE_MODE_NON_SECURE=1 -c -I../../Core/Inc -I../../AZURE_RTOS/App -I../../USBX/App -I../../USBX/Target -I../../OpenBootloader/App -I../../OpenBootloader/Target -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/OpenBootloader/Modules/USART -I../../../../../../Middlewares/ST/OpenBootloader/Modules/I2C -I../../../../../../Middlewares/ST/OpenBootloader/Modules/SPI -I../../../../../../Middlewares/ST/OpenBootloader/Modules/FDCAN -I../../../../../../Middlewares/ST/OpenBootloader/Modules/Mem -I../../../../../../Middlewares/ST/OpenBootloader/Modules/USB -I../../../../../../Middlewares/ST/OpenBootloader/Core -I../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../Middlewares/ST/threadx/ports/cortex_m33/gnu/inc -I../../../../../../Middlewares/ST/usbx/common/core/inc -I../../../../../../Middlewares/ST/usbx/ports/generic/inc -I../../../../../../Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../../../Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Core/stm32u5xx_hal_msp.o: /Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Projects/B-U585I-IOT02A/Applications/OpenBootloader/Core/Src/stm32u5xx_hal_msp.c Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSBPD_PORT_COUNT=1 -DSTM32U585xx -DUSE_HAL_DRIVER -DUSBPD_THREADX -DUSE_FULL_LL_DRIVER -DUSBPDCORE_LIB_NO_PD -DTCPP0203_SUPPORT -D_SNK -DUX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_B_U585I_IOT02A -DTX_SINGLE_MODE_NON_SECURE=1 -c -I../../Core/Inc -I../../AZURE_RTOS/App -I../../USBX/App -I../../USBX/Target -I../../OpenBootloader/App -I../../OpenBootloader/Target -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/OpenBootloader/Modules/USART -I../../../../../../Middlewares/ST/OpenBootloader/Modules/I2C -I../../../../../../Middlewares/ST/OpenBootloader/Modules/SPI -I../../../../../../Middlewares/ST/OpenBootloader/Modules/FDCAN -I../../../../../../Middlewares/ST/OpenBootloader/Modules/Mem -I../../../../../../Middlewares/ST/OpenBootloader/Modules/USB -I../../../../../../Middlewares/ST/OpenBootloader/Core -I../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../Middlewares/ST/threadx/ports/cortex_m33/gnu/inc -I../../../../../../Middlewares/ST/usbx/common/core/inc -I../../../../../../Middlewares/ST/usbx/ports/generic/inc -I../../../../../../Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../../../Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Core/stm32u5xx_hal_timebase_tim.o: /Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Projects/B-U585I-IOT02A/Applications/OpenBootloader/Core/Src/stm32u5xx_hal_timebase_tim.c Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSBPD_PORT_COUNT=1 -DSTM32U585xx -DUSE_HAL_DRIVER -DUSBPD_THREADX -DUSE_FULL_LL_DRIVER -DUSBPDCORE_LIB_NO_PD -DTCPP0203_SUPPORT -D_SNK -DUX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_B_U585I_IOT02A -DTX_SINGLE_MODE_NON_SECURE=1 -c -I../../Core/Inc -I../../AZURE_RTOS/App -I../../USBX/App -I../../USBX/Target -I../../OpenBootloader/App -I../../OpenBootloader/Target -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/OpenBootloader/Modules/USART -I../../../../../../Middlewares/ST/OpenBootloader/Modules/I2C -I../../../../../../Middlewares/ST/OpenBootloader/Modules/SPI -I../../../../../../Middlewares/ST/OpenBootloader/Modules/FDCAN -I../../../../../../Middlewares/ST/OpenBootloader/Modules/Mem -I../../../../../../Middlewares/ST/OpenBootloader/Modules/USB -I../../../../../../Middlewares/ST/OpenBootloader/Core -I../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../Middlewares/ST/threadx/ports/cortex_m33/gnu/inc -I../../../../../../Middlewares/ST/usbx/common/core/inc -I../../../../../../Middlewares/ST/usbx/ports/generic/inc -I../../../../../../Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../../../Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Core/stm32u5xx_it.o: /Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Projects/B-U585I-IOT02A/Applications/OpenBootloader/Core/Src/stm32u5xx_it.c Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSBPD_PORT_COUNT=1 -DSTM32U585xx -DUSE_HAL_DRIVER -DUSBPD_THREADX -DUSE_FULL_LL_DRIVER -DUSBPDCORE_LIB_NO_PD -DTCPP0203_SUPPORT -D_SNK -DUX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_B_U585I_IOT02A -DTX_SINGLE_MODE_NON_SECURE=1 -c -I../../Core/Inc -I../../AZURE_RTOS/App -I../../USBX/App -I../../USBX/Target -I../../OpenBootloader/App -I../../OpenBootloader/Target -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/OpenBootloader/Modules/USART -I../../../../../../Middlewares/ST/OpenBootloader/Modules/I2C -I../../../../../../Middlewares/ST/OpenBootloader/Modules/SPI -I../../../../../../Middlewares/ST/OpenBootloader/Modules/FDCAN -I../../../../../../Middlewares/ST/OpenBootloader/Modules/Mem -I../../../../../../Middlewares/ST/OpenBootloader/Modules/USB -I../../../../../../Middlewares/ST/OpenBootloader/Core -I../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../Middlewares/ST/threadx/ports/cortex_m33/gnu/inc -I../../../../../../Middlewares/ST/usbx/common/core/inc -I../../../../../../Middlewares/ST/usbx/ports/generic/inc -I../../../../../../Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../../../Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Core/%.o Application/Core/%.su Application/Core/%.cyclo: ../Application/Core/%.c Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSBPD_PORT_COUNT=1 -DSTM32U585xx -DUSE_HAL_DRIVER -DUSBPD_THREADX -DUSE_FULL_LL_DRIVER -DUSBPDCORE_LIB_NO_PD -DTCPP0203_SUPPORT -D_SNK -DUX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_B_U585I_IOT02A -DTX_SINGLE_MODE_NON_SECURE=1 -c -I../../Core/Inc -I../../AZURE_RTOS/App -I../../USBX/App -I../../USBX/Target -I../../OpenBootloader/App -I../../OpenBootloader/Target -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/OpenBootloader/Modules/USART -I../../../../../../Middlewares/ST/OpenBootloader/Modules/I2C -I../../../../../../Middlewares/ST/OpenBootloader/Modules/SPI -I../../../../../../Middlewares/ST/OpenBootloader/Modules/FDCAN -I../../../../../../Middlewares/ST/OpenBootloader/Modules/Mem -I../../../../../../Middlewares/ST/OpenBootloader/Modules/USB -I../../../../../../Middlewares/ST/OpenBootloader/Core -I../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../Middlewares/ST/threadx/ports/cortex_m33/gnu/inc -I../../../../../../Middlewares/ST/usbx/common/core/inc -I../../../../../../Middlewares/ST/usbx/ports/generic/inc -I../../../../../../Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../../../Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Core/tx_initialize_low_level.o: /Users/AtomicOwner/Documents/UCLA/E96I/STM32CubeU5/Projects/B-U585I-IOT02A/Applications/OpenBootloader/Core/Src/tx_initialize_low_level.S Application/Core/subdir.mk
	arm-none-eabi-gcc -mcpu=cortex-m33 -g3 -DDEBUG -DTX_SINGLE_MODE_NON_SECURE=1 -c -x assembler-with-cpp -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"

clean: clean-Application-2f-Core

clean-Application-2f-Core:
	-$(RM) ./Application/Core/main.cyclo ./Application/Core/main.d ./Application/Core/main.o ./Application/Core/main.su ./Application/Core/stm32u5xx_hal_msp.cyclo ./Application/Core/stm32u5xx_hal_msp.d ./Application/Core/stm32u5xx_hal_msp.o ./Application/Core/stm32u5xx_hal_msp.su ./Application/Core/stm32u5xx_hal_timebase_tim.cyclo ./Application/Core/stm32u5xx_hal_timebase_tim.d ./Application/Core/stm32u5xx_hal_timebase_tim.o ./Application/Core/stm32u5xx_hal_timebase_tim.su ./Application/Core/stm32u5xx_it.cyclo ./Application/Core/stm32u5xx_it.d ./Application/Core/stm32u5xx_it.o ./Application/Core/stm32u5xx_it.su ./Application/Core/syscalls.cyclo ./Application/Core/syscalls.d ./Application/Core/syscalls.o ./Application/Core/syscalls.su ./Application/Core/sysmem.cyclo ./Application/Core/sysmem.d ./Application/Core/sysmem.o ./Application/Core/sysmem.su ./Application/Core/tx_initialize_low_level.d ./Application/Core/tx_initialize_low_level.o

.PHONY: clean-Application-2f-Core

